// tokenize-colors.mjs — lift every oklch() literal in feature CSS into a primitive
// color token so no raw color literal remains outside the token files. Values are
// preserved byte-for-byte, so tokenization causes zero visual change.
//
// Usage: node scripts/tokenize-colors.mjs [--check]
//   (default) rewrites feature CSS + regenerates src/styles/palette.css
//   --check    fails if any feature CSS still contains an oklch literal
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const SRC = new URL('../src/', import.meta.url).pathname;
const PALETTE_FILE = join(SRC, 'styles/palette.css');
const TOKEN_FILES = new Set(['styles/tokens.css', 'styles/palette.css']);
const OKLCH = /oklch\([^)]*\)/g;

// walk returns every .css file under src.
function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full));
    } else if (name.endsWith('.css')) {
      out.push(full);
    }
  }
  return out;
}

// tokenName derives a stable, collision-free token name from an oklch literal.
function tokenName(literal) {
  const inner = literal.slice('oklch('.length, -1).trim();
  const [color, alpha] = inner.split('/').map((part) => part.trim());
  const [l, c, h] = color.split(/\s+/);
  const norm = (value) => (value ?? '0').replace('%', '').replace(/\./g, 'p');
  let name = `--tone-${norm(l)}-${norm(c)}-${norm(h)}`;
  if (alpha) {
    name += `-a${norm(alpha)}`;
  }
  return name;
}

const files = walk(SRC).filter((file) => !TOKEN_FILES.has(relative(SRC, file)));
const isCheck = process.argv.includes('--check');

// First pass: collect the distinct literal -> token map across all feature CSS.
const map = new Map();
for (const file of files) {
  const css = readFileSync(file, 'utf8');
  for (const match of css.matchAll(OKLCH)) {
    const literal = match[0];
    if (!map.has(literal)) {
      map.set(literal, tokenName(literal));
    }
  }
}

if (isCheck) {
  const offenders = files.filter((file) => /oklch\(/.test(readFileSync(file, 'utf8')));
  if (offenders.length) {
    console.error('Raw oklch() literals remain in:', offenders.map((f) => relative(SRC, f)).join(', '));
    process.exit(1);
  }
  console.log('No raw oklch() literals outside token files.');
  process.exit(0);
}

// Emit the generated primitive palette (sorted for a stable diff).
const entries = [...map.entries()].sort((a, b) => a[1].localeCompare(b[1]));
const palette = [
  '/*',
  ' * palette.css — GENERATED by scripts/tokenize-colors.mjs. Do not edit by hand.',
  ' * Primitive color tokens: one per distinct oklch literal used across feature CSS.',
  ' * Values are preserved exactly; semantic tokens in tokens.css alias these.',
  ' * Regenerate with: node scripts/tokenize-colors.mjs',
  ' */',
  '@layer tokens {',
  '  :root {',
  ...entries.map(([literal, name]) => `    ${name}: ${literal};`),
  '  }',
  '}',
  '',
].join('\n');
writeFileSync(PALETTE_FILE, palette);

// Second pass: replace every literal with its token reference.
let replaced = 0;
for (const file of files) {
  const css = readFileSync(file, 'utf8');
  const next = css.replace(OKLCH, (literal) => {
    replaced += 1;
    return `var(${map.get(literal)})`;
  });
  if (next !== css) {
    writeFileSync(file, next);
  }
}

console.log(`Tokenized ${replaced} literals into ${map.size} primitive tokens across ${files.length} CSS files.`);
console.log(`Wrote ${relative(SRC, PALETTE_FILE)}.`);
