package config

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

// TestLoadFromEnvObservability verifies observability environment settings are parsed into config.
func TestLoadFromEnvObservability(t *testing.T) {
	t.Setenv("ACCOUNTING_LOG_PUSH_API", "https://alerts.example.test/push")
	t.Setenv("ACCOUNTING_LOG_PUSH_TOKEN", "secret-token")
	t.Setenv("ACCOUNTING_LOG_PUSH_TYPE", "telegram")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_ALLOWED_DOMAINS", "example.com, internal.test")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_FORCE_SMTP_TLS_VERIFY", "false")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_LOGIN_ENABLED", "false")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_REGISTER_ENABLED", "true")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_SMTP_FROM", "noreply@example.com")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_SMTP_HOST", "smtp.example.com")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_SMTP_PASSWORD", "smtp-secret")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_SMTP_PORT", "465")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_SMTP_USERNAME", "smtp-user")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_VERIFICATION_REQUIRED", "true")
	t.Setenv("ACCOUNTING_AUTH_EMAIL_VERIFICATION_TTL", "20m")
	t.Setenv("ACCOUNTING_AUTH_PASSKEY_ENABLED", "false")
	t.Setenv("ACCOUNTING_AUTH_PASSKEY_RP_DISPLAY_NAME", "Accounting Test")
	t.Setenv("ACCOUNTING_AUTH_PASSKEY_RP_ID", "accounts.example.com")
	t.Setenv("ACCOUNTING_AUTH_PASSKEY_RP_ORIGIN", "https://accounts.example.com")
	t.Setenv("ACCOUNTING_AUTH_TOTP_ENABLED", "true")
	t.Setenv("ACCOUNTING_AUTH_TOTP_ISSUER", "Accounting Test")
	t.Setenv("ACCOUNTING_AUTH_TOTP_REPLAY_CACHE_DURATION", "45s")
	t.Setenv("ACCOUNTING_AUTH_TURNSTILE_ENABLED", "true")
	t.Setenv("ACCOUNTING_AUTH_TURNSTILE_LOGIN_MODE", "after_failure")
	t.Setenv("ACCOUNTING_AUTH_TURNSTILE_SECRET_KEY", "turnstile-secret")
	t.Setenv("ACCOUNTING_AUTH_TURNSTILE_SITE_KEY", "turnstile-site")
	t.Setenv("ACCOUNTING_AUTH_TURNSTILE_VERIFY_URL", "https://turnstile.example.test/siteverify")
	t.Setenv("ACCOUNTING_ENABLE_PPROF", "true")
	t.Setenv("ACCOUNTING_PPROF_LISTEN", "127.0.0.1:6061")
	t.Setenv("ACCOUNTING_SHUTDOWN_TIMEOUT", "15s")
	t.Setenv("ACCOUNTING_OTEL_ENABLED", "true")
	t.Setenv("ACCOUNTING_OTEL_EXPORTER_OTLP_ENDPOINT", "https://collector.example.test:4318")
	t.Setenv("ACCOUNTING_OTEL_ENVIRONMENT", "staging")
	t.Setenv("ACCOUNTING_OTEL_EXPORTER_OTLP_INSECURE", "false")
	t.Setenv("ACCOUNTING_OTEL_SERVICE_NAME", "accounting-test")

	cfg := LoadFromEnv()

	require.Equal(t, "https://alerts.example.test/push", cfg.AlertPusher.API)
	require.Equal(t, "secret-token", cfg.AlertPusher.Token)
	require.Equal(t, "telegram", cfg.AlertPusher.Type)
	require.Equal(t, []string{"example.com", "internal.test"}, cfg.Auth.Email.AllowedRegistrationDomains)
	require.False(t, cfg.Auth.Email.ForceSMTPVerifyTLS)
	require.False(t, cfg.Auth.Email.LoginEnabled)
	require.True(t, cfg.Auth.Email.RegisterEnabled)
	require.Equal(t, "noreply@example.com", cfg.Auth.Email.SMTPFrom)
	require.Equal(t, "smtp.example.com", cfg.Auth.Email.SMTPHost)
	require.Equal(t, "smtp-secret", cfg.Auth.Email.SMTPPassword)
	require.Equal(t, 465, cfg.Auth.Email.SMTPPort)
	require.Equal(t, "smtp-user", cfg.Auth.Email.SMTPUsername)
	require.True(t, cfg.Auth.Email.VerificationRequired)
	require.Equal(t, 20*time.Minute, cfg.Auth.Email.VerificationTTL)
	require.False(t, cfg.Auth.Passkey.Enabled)
	require.Equal(t, "Accounting Test", cfg.Auth.Passkey.RPDisplayName)
	require.Equal(t, "accounts.example.com", cfg.Auth.Passkey.RPID)
	require.Equal(t, "https://accounts.example.com", cfg.Auth.Passkey.RPOrigin)
	require.True(t, cfg.Auth.TOTP.Enabled)
	require.Equal(t, "Accounting Test", cfg.Auth.TOTP.Issuer)
	require.Equal(t, 45*time.Second, cfg.Auth.TOTP.ReplayCacheDuration)
	require.True(t, cfg.Auth.Turnstile.Enabled)
	require.Equal(t, "after_failure", cfg.Auth.Turnstile.LoginMode)
	require.Equal(t, "turnstile-secret", cfg.Auth.Turnstile.SecretKey)
	require.Equal(t, "turnstile-site", cfg.Auth.Turnstile.SiteKey)
	require.Equal(t, "https://turnstile.example.test/siteverify", cfg.Auth.Turnstile.VerifyURL)
	require.True(t, cfg.Pprof.Enabled)
	require.Equal(t, "127.0.0.1:6061", cfg.Pprof.Listen)
	require.Equal(t, 15*time.Second, cfg.Shutdown.Timeout)
	require.True(t, cfg.Telemetry.Enabled)
	require.Equal(t, "collector.example.test:4318", cfg.Telemetry.Endpoint)
	require.Equal(t, "staging", cfg.Telemetry.Environment)
	require.False(t, cfg.Telemetry.Insecure)
	require.Equal(t, "accounting-test", cfg.Telemetry.ServiceName)
}
